//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkspaceLauncher {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W1")]
        public string workspaceOneBtn {
            get {
                return ((string)(this["workspaceOneBtn"]));
            }
            set {
                this["workspaceOneBtn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W2")]
        public string workspaceTwoBtn {
            get {
                return ((string)(this["workspaceTwoBtn"]));
            }
            set {
                this["workspaceTwoBtn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W3")]
        public string workspaceThreeBtn {
            get {
                return ((string)(this["workspaceThreeBtn"]));
            }
            set {
                this["workspaceThreeBtn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W4")]
        public string workspaceFourBtn {
            get {
                return ((string)(this["workspaceFourBtn"]));
            }
            set {
                this["workspaceFourBtn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W5")]
        public string workspaceFiveBtn {
            get {
                return ((string)(this["workspaceFiveBtn"]));
            }
            set {
                this["workspaceFiveBtn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W1 App Name")]
        public string W1SelectedAppName {
            get {
                return ((string)(this["W1SelectedAppName"]));
            }
            set {
                this["W1SelectedAppName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W1 File Name")]
        public string W1SelectedFileName {
            get {
                return ((string)(this["W1SelectedFileName"]));
            }
            set {
                this["W1SelectedFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W1 File Path")]
        public string W1SelectedFilePath {
            get {
                return ((string)(this["W1SelectedFilePath"]));
            }
            set {
                this["W1SelectedFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W1 App Path")]
        public string W1SelectedAppPath {
            get {
                return ((string)(this["W1SelectedAppPath"]));
            }
            set {
                this["W1SelectedAppPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W2 App Name")]
        public string W2SelectedAppName {
            get {
                return ((string)(this["W2SelectedAppName"]));
            }
            set {
                this["W2SelectedAppName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W2 File Name")]
        public string W2SelectedFileName {
            get {
                return ((string)(this["W2SelectedFileName"]));
            }
            set {
                this["W2SelectedFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W2 File Path")]
        public string W2SelectedFilePath {
            get {
                return ((string)(this["W2SelectedFilePath"]));
            }
            set {
                this["W2SelectedFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W2 App Path")]
        public string W2SelectedAppPath {
            get {
                return ((string)(this["W2SelectedAppPath"]));
            }
            set {
                this["W2SelectedAppPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string W1WorkspaceItemsJsonString {
            get {
                return ((string)(this["W1WorkspaceItemsJsonString"]));
            }
            set {
                this["W1WorkspaceItemsJsonString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string W2WorkspaceItemsJsonString {
            get {
                return ((string)(this["W2WorkspaceItemsJsonString"]));
            }
            set {
                this["W2WorkspaceItemsJsonString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string W3WorkspaceItemsJsonString {
            get {
                return ((string)(this["W3WorkspaceItemsJsonString"]));
            }
            set {
                this["W3WorkspaceItemsJsonString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string W4WorkspaceItemsJsonString {
            get {
                return ((string)(this["W4WorkspaceItemsJsonString"]));
            }
            set {
                this["W4WorkspaceItemsJsonString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string W5WorkspaceItemsJsonString {
            get {
                return ((string)(this["W5WorkspaceItemsJsonString"]));
            }
            set {
                this["W5WorkspaceItemsJsonString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W3 App Name")]
        public string W3SelectedAppName {
            get {
                return ((string)(this["W3SelectedAppName"]));
            }
            set {
                this["W3SelectedAppName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W3 App Path")]
        public string W3SelectedAppPath {
            get {
                return ((string)(this["W3SelectedAppPath"]));
            }
            set {
                this["W3SelectedAppPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W3 File Name")]
        public string W3SelectedFileName {
            get {
                return ((string)(this["W3SelectedFileName"]));
            }
            set {
                this["W3SelectedFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W3 File Path")]
        public string W3SelectedFilePath {
            get {
                return ((string)(this["W3SelectedFilePath"]));
            }
            set {
                this["W3SelectedFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W4 App Name")]
        public string W4SelectedAppName {
            get {
                return ((string)(this["W4SelectedAppName"]));
            }
            set {
                this["W4SelectedAppName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W4 App Path")]
        public string W4SelectedAppPath {
            get {
                return ((string)(this["W4SelectedAppPath"]));
            }
            set {
                this["W4SelectedAppPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W4 File Name")]
        public string W4SelectedFileName {
            get {
                return ((string)(this["W4SelectedFileName"]));
            }
            set {
                this["W4SelectedFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W4 File Path")]
        public string W4SelectedFilePath {
            get {
                return ((string)(this["W4SelectedFilePath"]));
            }
            set {
                this["W4SelectedFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W5 App Name")]
        public string W5SelectedAppName {
            get {
                return ((string)(this["W5SelectedAppName"]));
            }
            set {
                this["W5SelectedAppName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W5 App Path")]
        public string W5SelectedAppPath {
            get {
                return ((string)(this["W5SelectedAppPath"]));
            }
            set {
                this["W5SelectedAppPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W5 File Name")]
        public string W5SelectedFileName {
            get {
                return ((string)(this["W5SelectedFileName"]));
            }
            set {
                this["W5SelectedFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W5 File Path")]
        public string W5SelectedFilePath {
            get {
                return ((string)(this["W5SelectedFilePath"]));
            }
            set {
                this["W5SelectedFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SelectStartupCheckboxValue {
            get {
                return ((bool)(this["SelectStartupCheckboxValue"]));
            }
            set {
                this["SelectStartupCheckboxValue"] = value;
            }
        }
    }
}
