# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  win: circleci/windows@5.0

# Define a job to be invoked later in a workflow.
jobs:
  build:
    executor: win/server-2022

    # Add steps to the job
    # See: https://circleci.com/docs/jobs-steps/#steps-overview & https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      
      # Restore NuGet packages
      - run:
          name: Restore NuGet Packages
          command: dotnet restore WorkspaceLauncher.sln

      # Build the project in Release mode
      - run:
          name: Build Solution
          command: dotnet build WorkspaceLauncher.sln --configuration Release

      # Publish using ClickOnce (with MSBuild)
      - run:
          name: Publish ClickOnce
          command: |
            msbuild WorkspaceLauncher/WorkspaceLauncher.csproj /target:publish /p:Configuration=Release /p:PublishDir=bin\Publish

      # Zip the Publish folder and rename it to WorkspaceLauncher.zip
      - run:
          name: Zip the Publish folder and rename
          command: powershell Compress-Archive -Path WorkspaceLauncher/bin/Publish/* -DestinationPath WorkspaceLauncher/bin/WorkspaceLauncher.zip

      # Use the environment variables
      - run:
          name: Use Environment Variables
          command: |
            echo 'export NETLIFY_AUTH_TOKEN="$NETLIFY_AUTH_TOKEN"' >> "$BASH_ENV"
            echo 'export NETLIFY_SITE_ID="$NETLIFY_SITE_ID"' >> "$BASH_ENV"
      
      # testing
      - run:
          name: variable test
          command: |
            echo "$NETLIFY_AUTH_TOKEN"
            echo "$NETLIFY_SITE_ID"
            echo "${NETLIFY_AUTH_TOKEN}"
            echo "${NETLIFY_SITE_ID}"

      # Deploy the zip file to Netlify
      - run:
          name: Deploy to Netlify
          #filePath in CircleCi
          command: |
            $filePath = "WorkspaceLauncher/bin/WorkspaceLauncher.zip"
            $uri = "https://api.netlify.com/api/v1/sites/$NETLIFY_SITE_ID/deploys"
            $headers = @{
                "Content-Type" = "application/zip"
                "Authorization" = "Bearer $NETLIFY_AUTH_TOKEN"
            }
            Invoke-WebRequest -Uri $uri -Method Post -Headers $headers -InFile $filePath
            
workflows:
  version: 2
  clickonce-deployment:
    jobs:
      - build
