# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  win: circleci/windows@2.2.0

# Define a job to be invoked later in a workflow.
jobs:
  build:
    executor:
      name: win/default
    # Add steps to the job
    # See: https://circleci.com/docs/jobs-steps/#steps-overview & https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      
      # Install .NET SDK
      - run:
          name: Install .NET SDK
          command: |
            choco install dotnetcore-sdk -y
            dotnet --version

      # Restore NuGet packages
      - run:
          name: Restore NuGet Packages
          command: dotnet restore WorkspaceLauncher.sln

      # Build the project in Release mode
      - run:
          name: Build Solution
          command: dotnet build WorkspaceLauncher.sln --configuration Release

      # Publish using ClickOnce (with MSBuild)
      - run:
          name: Publish ClickOnce
          command: |
            msbuild WorkspaceLauncher/WorkspaceLauncher.csproj /target:publish /p:Configuration=Release /p:PublishDir=bin\Publish

      # Zip the Publish folder and rename it to WorkspaceLauncher.zip
      - run:
          name: Zip the Publish folder and rename
          command: powershell Compress-Archive -Path WorkspaceLauncher/bin/Publish/* -DestinationPath WorkspaceLauncher/bin/WorkspaceLauncher.zip

      # Deploy the zip file to Netlify
      - run:
          name: Deploy to Netlify
          command: |
            curl -H "Authorization: Bearer $NETLIFY_AUTH_TOKEN" \
                 -F "file=@WorkspaceLauncher/bin/WorkspaceLauncher.zip" \
                 https://api.netlify.com/api/v1/sites/$NETLIFY_SITE_ID/deploys

workflows:
  version: 2
  clickonce-deployment:
    jobs:
      - build
