//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkspaceUI {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W1")]
        public string workspaceOneBtn {
            get {
                return ((string)(this["workspaceOneBtn"]));
            }
            set {
                this["workspaceOneBtn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W2")]
        public string workspaceTwoBtn {
            get {
                return ((string)(this["workspaceTwoBtn"]));
            }
            set {
                this["workspaceTwoBtn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W3")]
        public string workspaceThreeBtn {
            get {
                return ((string)(this["workspaceThreeBtn"]));
            }
            set {
                this["workspaceThreeBtn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W4")]
        public string workspaceFourBtn {
            get {
                return ((string)(this["workspaceFourBtn"]));
            }
            set {
                this["workspaceFourBtn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W5")]
        public string workspaceFiveBtn {
            get {
                return ((string)(this["workspaceFiveBtn"]));
            }
            set {
                this["workspaceFiveBtn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W1 App")]
        public string W1SelectedAppName {
            get {
                return ((string)(this["W1SelectedAppName"]));
            }
            set {
                this["W1SelectedAppName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W1 File")]
        public string W1SelectedFileName {
            get {
                return ((string)(this["W1SelectedFileName"]));
            }
            set {
                this["W1SelectedFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W1 File Path")]
        public string W1SelectedFilePath {
            get {
                return ((string)(this["W1SelectedFilePath"]));
            }
            set {
                this["W1SelectedFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W1 App Path")]
        public string W1SelectedAppPath {
            get {
                return ((string)(this["W1SelectedAppPath"]));
            }
            set {
                this["W1SelectedAppPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W2 App")]
        public string W2SelectedAppName {
            get {
                return ((string)(this["W2SelectedAppName"]));
            }
            set {
                this["W2SelectedAppName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W2 File")]
        public string W2SelectedFileName {
            get {
                return ((string)(this["W2SelectedFileName"]));
            }
            set {
                this["W2SelectedFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W2 File Path")]
        public string W2SelectedFilePath {
            get {
                return ((string)(this["W2SelectedFilePath"]));
            }
            set {
                this["W2SelectedFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W2 App Path")]
        public string W2SelectedAppPath {
            get {
                return ((string)(this["W2SelectedAppPath"]));
            }
            set {
                this["W2SelectedAppPath"] = value;
            }
        }
    }
}
